class MicrowaveOven {
public static void main(String samsung[]){
      System.out.println("Convection Microwave Oven: Ideal for everyday cooking needs, baking along with grilling, reheating, defrosting");
	  System.out.println("Capacity: 21 Litres – Suitable for families with 3–4 members.Manufacturer Warranty: 1 year on product, 10 Years on Ceramic enamel cavity. (T&C Apply) | Enjoy peace of mind with Samsung’s long-lasting ceramic enamel cavity ensuring durability, easy cleaning, and hygienic usage.");
	  System.out.println("Manufacturer Warranty: 1 year on product, 10 Years on Ceramic enamel cavity. (T&C Apply) | Enjoy peace of mind with Samsung’s long-lasting ceramic enamel cavity ensuring durability, easy cleaning, and hygienic usage.Number of Programs: 6 Power Levels with Multiple Cooking Modes. | Panel: Touch key membrane panel allows precise control and effortless cleaning. Built-in Auto Cook and Auto Defrost features simplify complex cooking steps.");
	  System.out.println("Number of Programs: 6 Power Levels with Multiple Cooking Modes. | Panel: Touch key membrane panel allows precise control and effortless cleaning. Built-in Auto Cook and Auto Defrost features simplify complex cooking steps.Energy Consumption: Microwave: 1200 W | Grill: 1100 W | Convection: 1700 W | Max: 2350 W | Efficient performance suitable for daily use with lower cooking time and higher energy efficiency.");
	  System.out.println("Energy Consumption: Microwave: 1200 W | Grill: 1100 W | Convection: 1700 W | Max: 2350 W | Efficient performance suitable for daily use with lower cooking time and higher energy efficiency.Auto Cook Menus & Auto Defrost Programs | Ideal for Indian Recipes The microwave includes several one-touch cooking and defrosting menus optimized for everyday recipes like rice, vegetables, snacks, and desserts. Simplifies cooking with preset temperature and timing combinations.");
	  System.out.println("Auto Cook Menus & Auto Defrost Programs | Ideal for Indian Recipes The microwave includes several one-touch cooking and defrosting menus optimized for everyday recipes like rice, vegetables, snacks, and desserts. Simplifies cooking with preset temperature and timing combinations.Special Features: Child Safety Lock | Auto Defrost | Auto Cook | Programmable | Digital Clock | Turntable Functionality | Child Safety Lock ensures safe usage in homes with kids. Auto Defrost ensures even thawing. Digital Clock keeps you informed and organized.");
	  System.out.println("Special Features: Child Safety Lock | Auto Defrost | Auto Cook | Programmable | Digital Clock | Turntable Functionality | Child Safety Lock ensures safe usage in homes with kids. Auto Defrost ensures even thawing. Digital Clock keeps you informed and organized.");
	  }
}